### ISSUE TITLE
Hold Boot and Tap Reset can't enter usbdrive mode

### ISSUE THREAD

**Issue by mobius** [sipeed/M0sense_BL702_example#1]
no usbdrive appears on win & linux

**Comment by mtuxpe** [comment]
It is not well explained in the document:
1. You need to connect a jumper to the 3V and BOOT pins on the board.
2. Hold BOOT button and tap RESET. Finally, release the BOOT button.
4. Burn the m0sense_udisk_bl702_v0.1.bin  file located at
https://dl.sipeed.com/shareURL/Maix-Zero/Maix-Zero/7_Example_demos/default_firmware/
5. How to burn bin file : https://wiki.sipeed.com/hardware/en/maixzero/sense/start.html#Burn-bin-file
6. After burn remove the jumper

**Comment by mobius** [comment]
Thanks, it works

**Comment by taonyx** [comment]
Close this issue as it was solved and had no more updates.

**Comment by taonyx** [comment]
> It is not well explained in the document:
> 
>     1. You need to connect a jumper to the 3V and BOOT pins on the board.
> 
>     2. Hold BOOT button and tap RESET. Finally, release the BOOT button.
> 
>     3. Burn the m0sense_udisk_bl702_v0.1.bin  file located at
>        https://dl.sipeed.com/shareURL/Maix-Zero/Maix-Zero/7_Example_demos/default_firmware/
> 
>     4. How to burn bin file : https://wiki.sipeed.com/hardware/en/maixzero/sense/start.html#Burn-bin-file
> 
>     5. After burn remove the jumper

Best answer (👍^U^)👍
