### ISSUE TITLE
M0Sense demos

### ISSUE THREAD

**Issue by raffaeler** [sipeed/M0sense_BL702_example#3]
Where can I find the demos? See [here](https://www.indiegogo.com/projects/sipeed-maix-new-experience-to-risc-v-aiot-tinyml/x/30813922#/) at the "M0sense Models" paragraph.
Thanks

**Comment by taonyx** [comment]
Dear [raffaeler](https://github.com/raffaeler):

Sorry for that we have these demos can just only for show, the poor code quality make us not ready enough to open or release them.

But the Key Word Spotting is in a good situation, you can take reference to [TinyMaix](https://github.com/sipeed/TinyMaix/tree/main/examples/kws).

You can wait for some time also, we will release them as we can soon or maybe you can make a better one on your own, and that will help us a lot if you contribute it to us :)

Thanks for your question, we will pay it more attention.

Blessings on your day.

**Comment by raffaeler** [comment]
Hi @taorye I would love to contribute, but there is not a single document explaning where to start from.
I already had a discussion on TinyMaix and the fact there is no word about which model formats are supported where or how to use them. Without them, the amount of time to spend in trying is definitely too much.
If you don't provide some guideline and step-by-step, I strongly doubt someone will be able to contribute.
Good luck
